projects:
  - name: Politica dei Dati dell'INGV
    description: |
      Politica dei Dati dell'IStituto Nazionale di Geofisica e Vulcanologia (INGV)
    documents:
      - ingv-principi-della-politica-dei-dati-docs
      - ingv-accesso-aperto-ai-contributi-della-ricerca-docs
      - ingv-attuazione-della-politica-dei-dati-docs
      - ingv-data-policy-principles-docs
      - ingv-implementation-of-the-ingv-data-policy-docs
      - ingv-openaccess-to-scientific-contributions-docs

    short_name: accessoApertoContributi
    website: https://www.ingv.it
    tags:
      - digital
      - INGV
      - politica dei dati
      - open access
      - ricerca scientifica
