projects:
  - name: Principi della Politica dei Dati dell'INGV
    description: |
      Principi della Politica dei Dati dell'IStituto Nazionale di Geofisica e Vulcanologia (INGV)
    documents:
      - ingv-principi-della-politica-del-dati-docs
    short_name: PDP
    website: https://www.ingv.it
    tags:
      - digital
      - INGV
      - politica dei dati
